[doctest] run with "--help" for options
===============================================================================
main.cpp(0)
an empty test that will fail because of an exception

TEST CASE FAILED! (threw exception: unknown exception)

===============================================================================
main.cpp(0)
an empty test that will fail because of a std::exception

TEST CASE FAILED! (threw exception: Exception)

===============================================================================
main.cpp(0)
normal macros

main.cpp(0) FAILED! (threw exception: unknown exception)
  CHECK( throws(true) == 42 )

main.cpp(0) FAILED!
  CHECK( Approx(0.502) == 0.501 )
with expansion:
  CHECK( Approx( 0.502 ) == 0.501 )

TEST CASE FAILED! (threw exception: unknown exception)

===============================================================================
main.cpp(0)
normal macros with std::exception

main.cpp(0) FAILED! (threw exception: Exception)
  CHECK( throws_stdexcept(true) == 42 )

main.cpp(0) FAILED!
  CHECK( Approx(0.502) == 0.501 )
with expansion:
  CHECK( Approx( 0.502 ) == 0.501 )

TEST CASE FAILED! (threw exception: unknown exception)

===============================================================================
main.cpp(0)
exceptions-related macros

main.cpp(0) FAILED!
  CHECK_THROWS( throws(false) )

main.cpp(0) FAILED! (didn't throw at all)
  CHECK_THROWS_AS( throws(false), int )

main.cpp(0) FAILED! (threw exception: unknown exception)
  CHECK_THROWS_AS( throws(true), char )

main.cpp(0) FAILED! (threw exception: unknown exception)
  CHECK_NOTHROW( throws(true) )

===============================================================================
main.cpp(0)
exceptions-related macros for std::exception

main.cpp(0) FAILED!
  CHECK_THROWS( throws_stdexcept(false) )

main.cpp(0) FAILED! (didn't throw at all)
  CHECK_THROWS_AS( throws_stdexcept(false), std::exception )

main.cpp(0) FAILED! (threw exception: Exception)
  CHECK_THROWS_AS( throws_stdexcept(true), int )

main.cpp(0) FAILED! (threw exception: Exception)
  REQUIRE_NOTHROW( throws_stdexcept(true) )

===============================================================================
[doctest] test cases:    7 |    1 passed |    6 failed |    0 skipped
[doctest] assertions:   24 |   12 passed |   12 failed |
